"""
Professional PDF Report Generator for BugHunter Pro.
Generates a bug bounty report with cover page, executive summary, and detailed findings.
"""

import io
import logging
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# ── Severity definitions ──────────────────────────────────────────────────────
SEVERITY_CONFIG = {
    "critical": {"color": colors.HexColor("#E24B4A"), "cvss_range": "9.0–10.0", "label": "CRITICAL"},
    "high":     {"color": colors.HexColor("#EF9F27"), "cvss_range": "7.0–8.9",  "label": "HIGH"},
    "medium":   {"color": colors.HexColor("#3B82F6"), "cvss_range": "4.0–6.9",  "label": "MEDIUM"},
    "low":      {"color": colors.HexColor("#1D9E75"), "cvss_range": "0.1–3.9",  "label": "LOW"},
    "info":     {"color": colors.HexColor("#888888"), "cvss_range": "0.0",       "label": "INFO"},
}

# Remediation references per finding type
REFERENCES = {
    "xss":          ["OWASP A03:2021 Injection", "CWE-79", "https://owasp.org/Top10/A03_2021-Injection/"],
    "sqli":         ["OWASP A03:2021 Injection", "CWE-89", "https://owasp.org/Top10/A03_2021-Injection/"],
    "ssrf":         ["OWASP A10:2021 SSRF", "CWE-918", "https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/"],
    "cors":         ["OWASP A05:2021 Security Misconfiguration", "CWE-942"],
    "redirect":     ["OWASP A01:2021 Broken Access Control", "CWE-601"],
    "header":       ["OWASP A05:2021 Security Misconfiguration", "CWE-693"],
    "exposed_file": ["OWASP A05:2021 Security Misconfiguration", "CWE-538"],
    "secret_in_js": ["OWASP A02:2021 Cryptographic Failures", "CWE-312"],
    "takeover":     ["CWE-350", "HackerOne Subdomain Takeover"],
    "subdomain":    ["OWASP A05:2021 Security Misconfiguration"],
    "open_port":    ["OWASP A05:2021 Security Misconfiguration"],
    "admin_panel":  ["OWASP A05:2021 Security Misconfiguration", "CWE-284"],
}

DARK_BG  = colors.HexColor("#0D1117")
ACCENT   = colors.HexColor("#7F77DD")
WHITE    = colors.white
LIGHT_BG = colors.HexColor("#161B22")
BODY_TXT = colors.HexColor("#C9D1D9")


def generate_pdf(scan_id: str, domain: str, findings: list[dict], scan_started: str) -> bytes:
    """Generate a professional PDF report and return it as bytes."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title=f"Bug Bounty Report — {domain}",
        author="BugHunter Pro",
    )

    styles = _build_styles()
    story = []

    # ── Cover page ────────────────────────────────────────────────────────────
    story += _cover_page(domain, scan_id, scan_started, findings, styles)
    story.append(Spacer(1, 1 * cm))

    # ── Executive summary ─────────────────────────────────────────────────────
    story += _executive_summary(domain, findings, styles)
    story.append(Spacer(1, 0.5 * cm))

    # ── Summary table ─────────────────────────────────────────────────────────
    story += _summary_table(findings, styles)
    story.append(Spacer(1, 1 * cm))

    # ── Findings ──────────────────────────────────────────────────────────────
    story.append(Paragraph("Detailed Findings", styles["h1"]))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT))
    story.append(Spacer(1, 0.5 * cm))

    severity_order = ["critical", "high", "medium", "low", "info"]
    sorted_findings = sorted(
        findings,
        key=lambda f: severity_order.index(f.get("severity", "info")) if f.get("severity", "info") in severity_order else 99,
    )

    for i, finding in enumerate(sorted_findings, 1):
        story += _finding_block(i, finding, styles)
        story.append(Spacer(1, 0.8 * cm))

    # ── Disclaimer ────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#333")))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "This report was generated by BugHunter Pro for authorized security testing only. "
        "Unauthorized use of this tool or the techniques described herein may violate the "
        "Computer Misuse Act 1990 and equivalent legislation. Always obtain explicit written "
        "permission before testing any system you do not own.",
        styles["disclaimer"],
    ))

    doc.build(story)
    return buf.getvalue()


# ── Helpers ───────────────────────────────────────────────────────────────────

def _cover_page(domain, scan_id, scan_started, findings, styles):
    counts = _count_by_severity(findings)

    elements = [
        Spacer(1, 2 * cm),
        Paragraph("BUG BOUNTY REPORT", styles["cover_title"]),
        Spacer(1, 0.3 * cm),
        Paragraph(domain, styles["cover_domain"]),
        Spacer(1, 1 * cm),
        HRFlowable(width="100%", thickness=2, color=ACCENT),
        Spacer(1, 0.8 * cm),
        Paragraph(f"Scan ID: {scan_id}", styles["meta"]),
        Paragraph(f"Date: {scan_started}", styles["meta"]),
        Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles["meta"]),
        Spacer(1, 1.5 * cm),
        Paragraph("Vulnerability Summary", styles["h2"]),
        Spacer(1, 0.4 * cm),
    ]

    # Severity badge table
    badge_data = [[
        Paragraph(f"<b>{counts.get(s, 0)}</b><br/><font size='8'>{s.upper()}</font>", styles["badge_text"])
        for s in ["critical", "high", "medium", "low", "info"]
    ]]
    badge_table = Table(badge_data, colWidths=[3.2 * cm] * 5, rowHeights=[1.4 * cm])
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), SEVERITY_CONFIG["critical"]["color"]),
        ("BACKGROUND", (1, 0), (1, 0), SEVERITY_CONFIG["high"]["color"]),
        ("BACKGROUND", (2, 0), (2, 0), SEVERITY_CONFIG["medium"]["color"]),
        ("BACKGROUND", (3, 0), (3, 0), SEVERITY_CONFIG["low"]["color"]),
        ("BACKGROUND", (4, 0), (4, 0), SEVERITY_CONFIG["info"]["color"]),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TEXTCOLOR", (0, 0), (-1, -1), WHITE),
        ("FONTSIZE", (0, 0), (-1, -1), 16),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(badge_table)

    return elements


def _executive_summary(domain, findings, styles):
    counts = _count_by_severity(findings)
    total = len(findings)
    critical = counts.get("critical", 0)
    high = counts.get("high", 0)

    risk = "CRITICAL" if critical > 0 else ("HIGH" if high > 0 else "MEDIUM" if counts.get("medium", 0) > 0 else "LOW")

    summary_text = (
        f"A security assessment of <b>{domain}</b> identified <b>{total}</b> vulnerabilities across multiple attack categories. "
    )
    if critical:
        summary_text += f"<b>{critical} critical-severity</b> issue(s) require immediate remediation as they may allow full system compromise or sensitive data exposure. "
    if high:
        summary_text += f"<b>{high} high-severity</b> issue(s) pose significant risk and should be addressed as a priority. "
    summary_text += (
        "This report provides detailed reproduction steps, business impact analysis, "
        "and specific remediation guidance for each finding."
    )

    return [
        Paragraph("Executive Summary", styles["h1"]),
        HRFlowable(width="100%", thickness=1, color=ACCENT),
        Spacer(1, 0.4 * cm),
        Paragraph(summary_text, styles["body"]),
        Spacer(1, 0.3 * cm),
        Paragraph(f"Overall Risk Rating: <b>{risk}</b>", styles["risk_" + risk.lower()] if f"risk_{risk.lower()}" in styles else styles["body"]),
    ]


def _summary_table(findings, styles):
    counts = _count_by_severity(findings)
    cat_counts = {}
    for f in findings:
        cat = f.get("type", "other").replace("_", " ").title()
        cat_counts[cat] = cat_counts.get(cat, 0) + 1

    header = [Paragraph("<b>Category</b>", styles["table_header"]),
              Paragraph("<b>Count</b>", styles["table_header"]),
              Paragraph("<b>Severity</b>", styles["table_header"])]
    rows = [header]

    severity_for_type = {
        "Xss": "High", "Sqli": "Critical", "Ssrf": "Critical",
        "Cors": "High", "Redirect": "Medium", "Header": "Low–Medium",
        "Exposed File": "Critical–Medium", "Secret In Js": "Critical–High",
        "Takeover": "High", "Subdomain": "Info", "Open Port": "Low",
        "Admin Panel": "Medium",
    }
    for cat, cnt in sorted(cat_counts.items(), key=lambda x: x[1], reverse=True):
        rows.append([
            Paragraph(cat, styles["table_cell"]),
            Paragraph(str(cnt), styles["table_cell"]),
            Paragraph(severity_for_type.get(cat, "—"), styles["table_cell"]),
        ])

    t = Table(rows, colWidths=[9 * cm, 3 * cm, 5 * cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#1a1a2e"), colors.HexColor("#16213e")]),
        ("TEXTCOLOR", (0, 1), (-1, -1), BODY_TXT),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#333")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ]))

    return [
        Paragraph("Finding Categories", styles["h2"]),
        Spacer(1, 0.3 * cm),
        t,
    ]


def _finding_block(num: int, finding: dict, styles) -> list:
    severity = finding.get("severity", "info")
    sev_color = SEVERITY_CONFIG.get(severity, SEVERITY_CONFIG["info"])["color"]
    sev_label = SEVERITY_CONFIG.get(severity, SEVERITY_CONFIG["info"])["label"]
    cvss_range = SEVERITY_CONFIG.get(severity, SEVERITY_CONFIG["info"])["cvss_range"]
    ftype = finding.get("type", "other")
    refs = REFERENCES.get(ftype, [])

    elements = []

    # Finding header row
    header_data = [[
        Paragraph(f"<b>#{num}</b>", styles["finding_num"]),
        Paragraph(finding.get("title", "Unknown Finding"), styles["finding_title"]),
        Paragraph(sev_label, styles["sev_badge"]),
    ]]
    header_table = Table(header_data, colWidths=[1 * cm, 13.5 * cm, 2.5 * cm])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1a1a2e")),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (2, 0), (2, 0), sev_color),
        ("TEXTCOLOR", (2, 0), (2, 0), WHITE),
        ("ALIGN", (2, 0), (2, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(header_table)

    # Details
    url = finding.get("url", finding.get("evidence", {}).get("url", "N/A"))
    evidence = finding.get("evidence", {})

    detail_rows = [
        [Paragraph("<b>URL</b>",          styles["detail_label"]), Paragraph(_safe(url),                     styles["detail_value"])],
        [Paragraph("<b>Type</b>",         styles["detail_label"]), Paragraph(_safe(ftype.replace("_", " ").title()),styles["detail_value"])],
        [Paragraph("<b>CVSS Range</b>",   styles["detail_label"]), Paragraph(_safe(cvss_range),              styles["detail_value"])],
        [Paragraph("<b>Description</b>",  styles["detail_label"]), Paragraph(_safe(finding.get("description", "")), styles["detail_value"])],
        [Paragraph("<b>Impact</b>",       styles["detail_label"]), Paragraph(_impact_for(ftype),             styles["detail_value"])],
        [Paragraph("<b>Remediation</b>",  styles["detail_label"]), Paragraph(_safe(finding.get("remediation", "")), styles["detail_value"])],
    ]

    if evidence:
        evidence_str = "\n".join(f"{k}: {str(v)[:200]}" for k, v in evidence.items() if v)
        detail_rows.append([
            Paragraph("<b>Evidence</b>", styles["detail_label"]),
            Paragraph(_safe(evidence_str[:600]), styles["code"]),
        ])

    if refs:
        detail_rows.append([
            Paragraph("<b>References</b>", styles["detail_label"]),
            Paragraph("  •  ".join(_safe(r) for r in refs), styles["detail_value"]),
        ])

    detail_table = Table(detail_rows, colWidths=[3 * cm, 14 * cm])
    detail_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#0d1117")),
        ("TEXTCOLOR", (0, 0), (-1, -1), BODY_TXT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#222")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
    ]))
    elements.append(detail_table)

    return elements


# ── Style builder ─────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()
    return {
        "cover_title": ParagraphStyle("cover_title", fontSize=28, textColor=WHITE,
                                       fontName="Helvetica-Bold", alignment=TA_CENTER, spaceAfter=6),
        "cover_domain": ParagraphStyle("cover_domain", fontSize=18, textColor=ACCENT,
                                        fontName="Helvetica-Bold", alignment=TA_CENTER),
        "meta":         ParagraphStyle("meta", fontSize=10, textColor=colors.HexColor("#888"),
                                        fontName="Helvetica", alignment=TA_CENTER),
        "h1":           ParagraphStyle("h1", fontSize=16, textColor=ACCENT,
                                        fontName="Helvetica-Bold", spaceAfter=6),
        "h2":           ParagraphStyle("h2", fontSize=13, textColor=ACCENT,
                                        fontName="Helvetica-Bold", spaceAfter=4),
        "body":         ParagraphStyle("body", fontSize=10, textColor=BODY_TXT,
                                        fontName="Helvetica", leading=14),
        "disclaimer":   ParagraphStyle("disclaimer", fontSize=8, textColor=colors.HexColor("#666"),
                                        fontName="Helvetica-Oblique", alignment=TA_CENTER),
        "badge_text":   ParagraphStyle("badge_text", fontSize=14, textColor=WHITE,
                                        fontName="Helvetica-Bold", alignment=TA_CENTER),
        "table_header": ParagraphStyle("table_header", fontSize=9, textColor=WHITE,
                                        fontName="Helvetica-Bold"),
        "table_cell":   ParagraphStyle("table_cell", fontSize=9, textColor=BODY_TXT,
                                        fontName="Helvetica"),
        "finding_num":  ParagraphStyle("finding_num", fontSize=12, textColor=ACCENT,
                                        fontName="Helvetica-Bold", alignment=TA_CENTER),
        "finding_title":ParagraphStyle("finding_title", fontSize=11, textColor=WHITE,
                                        fontName="Helvetica-Bold"),
        "sev_badge":    ParagraphStyle("sev_badge", fontSize=9, textColor=WHITE,
                                        fontName="Helvetica-Bold", alignment=TA_CENTER),
        "detail_label": ParagraphStyle("detail_label", fontSize=9, textColor=colors.HexColor("#aaa"),
                                        fontName="Helvetica-Bold"),
        "detail_value": ParagraphStyle("detail_value", fontSize=9, textColor=BODY_TXT,
                                        fontName="Helvetica", leading=13),
        "code":         ParagraphStyle("code", fontSize=8, textColor=colors.HexColor("#7ee787"),
                                        fontName="Courier", leading=12),
        "risk_critical":ParagraphStyle("risk_c", fontSize=12, textColor=SEVERITY_CONFIG["critical"]["color"],
                                        fontName="Helvetica-Bold"),
        "risk_high":    ParagraphStyle("risk_h", fontSize=12, textColor=SEVERITY_CONFIG["high"]["color"],
                                        fontName="Helvetica-Bold"),
        "risk_medium":  ParagraphStyle("risk_m", fontSize=12, textColor=SEVERITY_CONFIG["medium"]["color"],
                                        fontName="Helvetica-Bold"),
        "risk_low":     ParagraphStyle("risk_l", fontSize=12, textColor=SEVERITY_CONFIG["low"]["color"],
                                        fontName="Helvetica-Bold"),
    }


def _count_by_severity(findings: list[dict]) -> dict:
    counts = {}
    for f in findings:
        s = f.get("severity", "info")
        counts[s] = counts.get(s, 0) + 1
    return counts


def _safe(text: str) -> str:
    if not text:
        return ""
    return (str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;"))


IMPACT_MAP = {
    "xss":          "Attackers can steal session cookies, redirect users, deface pages, or perform actions on behalf of victims.",
    "sqli":         "Complete database compromise — extraction of all data, authentication bypass, and potentially remote code execution.",
    "ssrf":         "Internal network access, cloud metadata exposure (IAM credentials), or lateral movement within the infrastructure.",
    "cors":         "Cross-origin API access allowing an attacker to read sensitive user data from victim browsers.",
    "redirect":     "Phishing attacks — users are redirected from trusted domain to attacker-controlled pages.",
    "header":       "Weakened browser security controls; increases risk of XSS, clickjacking, and MITM attacks.",
    "exposed_file": "Direct exposure of credentials, configuration, source code, or database backups.",
    "secret_in_js": "Exposed API keys can be abused to access third-party services, incurring costs or data breaches.",
    "takeover":     "Full control over subdomain — serve malicious content, steal cookies, send phishing emails from trusted domain.",
    "open_port":    "Additional attack surface; non-standard services may have weaker security controls.",
    "admin_panel":  "Exposed admin interfaces are prime targets for brute-force or credential stuffing attacks.",
}


def _impact_for(ftype: str) -> str:
    return IMPACT_MAP.get(ftype, "May expose sensitive data or allow unauthorized access.")
